sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tDxGeUBVevSi7yNmPme
    access-key-secret: S85VEWvKomjzo5Wx0P1FlnzYqTX0kC
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: mmmskytakeout
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx9c47ac23effc1afc
    secret: ee460b09e559be7ed6c4881a6347b484